const ACTIONS = {
  GET_DEPARTMENTS: 'GET_DEPARTMENTS',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_DEPARTMENTS_PRODUCTS: 'GET_DEPARTMENTS_PRODUCTS',
  GET_CATEGORY_PRODUCTS: 'GET_CATEGORY_PRODUCTS',
  GET_A_PRODUCTS: 'GET_A_PRODUCTS',
  GET_PRODUCT_REVIEWS: 'GET_PRODUCT_REVIEWS',
  SIGNED_UP_USER: 'SIGNED_UP_USER',
  AUTH_USER: 'AUTH_USER',
  CART_KEY: 'CART_KEY',
  CART_DETAILS: 'CART_DETAILS',
  CART_ITEMS: 'CART_ITEMS',
  CART_UPDATE: 'CART_UPDATE',
};

export default ACTIONS;
