const ACTIONS = {
  GET_DEPARTMENTS: 'GET_DEPARTMENTS',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_DEPARTMENTS_PRODUCTS: 'GET_DEPARTMENTS_PRODUCTS',
  GET_CATEGORY_PRODUCTS: 'GET_CATEGORY_PRODUCTS',
  GET_A_PRODUCTS: 'GET_A_PRODUCTS',
  GET_PRODUCT_REVIEWS: 'GET_PRODUCT_REVIEWS',
  SIGNED_UP_USER: 'SIGNED_UP_USER',
  AUTH_USER: 'AUTH_USER',
  CART_KEY: 'CART_KEY',
  CART_DETAILS: 'CART_DETAILS',
  CART_ITEMS: 'CART_ITEMS',
  CART_UPDATE: 'CART_UPDATE',
  AUTH_USER_ERROR: 'ACTIONS.AUTH_USER_ERROR',
  AUTH_USER_ERROR_ERASE: 'AUTH_USER_ERROR_ERASE',
  USER_DELIVER_INFO: 'USER_DELIVER_INFO',
  GENERATE_STRIP_TOKEN: 'GENERATE_STRIP_TOKEN',
  STRIPE_CHARGE_GENERATED: 'STRIPE_CHARGE_GENERATED',
  SPIN: 'SPIN',
  SEARCH_PRODUCT: 'SEARCH_PRODUCT',
};

export default ACTIONS;
